//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartViewHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Temp
    {
        public int Id { get; set; }
        public int Equipment_Parent_Id { get; set; }
        public Nullable<decimal> Temp_Range_Low { get; set; }
        public Nullable<decimal> Temp_Range_High { get; set; }
        public Nullable<int> Temp_Hour_Chk { get; set; }
        public string entry_user { get; set; }
        public string lst_mod_id { get; set; }
        public System.DateTime entry_ts { get; set; }
        public System.DateTime lst_mod_ts { get; set; }
    }
}
