//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartViewHealth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SVHDbContext : DbContext
    {
        public SVHDbContext()
            : base("name=SVHDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment_Temp_Log> Equipment_Temp_Log { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<HealthSystem> HealthSystems { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Equipment_Temp> Equipment_Temp { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<HealthSystemUserAssociation> HealthSystemUserAssociations { get; set; }
        public virtual DbSet<Equipment_Types> Equipment_Types { get; set; }
        public virtual DbSet<Equipment_EC_Meds> Equipment_EC_Meds { get; set; }
        public virtual DbSet<Equipment_EC_Supplies> Equipment_EC_Supplies { get; set; }
        public virtual DbSet<Equipment_SE_Tasks> Equipment_SE_Tasks { get; set; }
        public virtual DbSet<Equipment_SE_Log> Equipment_SE_Log { get; set; }
    }
}
